### ISSUE TITLE
A library dependency thats named lib<whatever> makes problems

### ISSUE THREAD

**Issue by mulle-kybernetik-tv** [mulle-sde/mulle-sde#55]
The problem is f.e. with libcaca, whose project named is determined to be "libcaca". So the actual library to be searched for is "liblibcaca" which fails.

### TODO

* not my problem, can be fixes with `mulle-sde dep set libcaca aliases caca` 
* automatically add libcaca and caca as aliases, if the project has a lib prefix. What's up with other platforms though.

Problems with legit names like "library" or "libre" ?

**Comment by mulle-nat** [comment]
Issue a warning, telling the user how to circumvent it.
