### ISSUE TITLE
mulle-sde dependency move command forgets that there are libraries

### ISSUE THREAD

**Issue by mulle-kybernetik-tv** [mulle-sde/mulle-sde#9]
Then "down" will move a dependency below a library, but that may not have visible consequences, since they are not visible in the list.

Solution: remove **move** from mulle-sde ?

**Comment by mulle-nat** [comment]
Other possibilites:

* remove "up/down" from dependency/library in mulle-sde only. Keep in mulle-sourcetree
* add a command move-above in mulle-sourcetree and use that
* move repeatedly until a change in list is affected or is on top/bottom
